### ISSUE TITLE
The version of Tensorflow and Keras

### ISSUE THREAD

**Issue by YaoZhang93** [MungoMeng/Survival-DeepMTS#1]
Hi Mingyuan,

Thanks for your nice work and I am trying to follow it. I am wondering which version of Tensorflow and Keras did you use?

Best regards,
Yao

**Comment by MungoMeng** [comment]
Hi Yao,

Thanks for your question.
Please use Keras == 2.3 and tensorflow == 1.15.

**Comment by YaoZhang93** [comment]
Thanks :)
