### ISSUE TITLE
Feature map visualization

### ISSUE THREAD

**Issue by codingS3b** [MungoMeng/Survival-DeepMTS#2]
Hi there! I really enjoyed reading your paper, very nice and interesting experiments that you did!
I just have a question regarding Figure S2 in your supplementary material, where you show feature map visualizations of Sur-HS, Sur-CasNet, MT-HS, MT-CasNet, and DeepMTS.
Which layer of your models was used to produce those feature maps? Or was an approach like Grad-CAM used for the creation of those heatmaps? Could you maybe also share the code to create those?
Thanks for providing some clues here!

**Comment by MungoMeng** [comment]
I appreciate your interest in our work!
The feature map visualization was produced by CAM, which is a weighted sum of many feature maps in multiple scales. I am sorry we did not preserve this code, but It should not be difficult to implement it -- Our model used GAP to integrate feature maps, which is directly applicable to CAM.

**Comment by codingS3b** [comment]
Thanks for clarifying that CAM was used, I think I can implement that without much trouble. As far as I know CAM and Grad-CAM require to specify a single layer whose feature maps will be averaged. Could you tell me which one you used? I assume it would be one of the maps obtained from the downsampling part of the Unet (e.g. x_out5 in your code [here](https://github.com/MungoMeng/Survival-DeepMTS/blob/ab8b0dd4e4c876e0597d443e0118ebce0bfe1dae/src/networks.py#L26))?

**Comment by MungoMeng** [comment]
Thanks for your further question. In fact, all feature maps that will be fed into the GAP can be weighted-summed. The corresponding weights are calculated based on the learned weights of FC layers.
